// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixissuewithBarcodeFeedmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixissuewithBarcodeFeedmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202305231335212_Fix issue with BarcodeFeed model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
