// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmailValuetomaxlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailValuetomaxlength));
        
        string IMigrationMetadata.Id
        {
            get { return "202403111410292_Email Value to max length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
